# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Theoni Koutropoulou
title: Data Scientist
email: theoni.koutropoulou@gmail.com
website: www.github.com/tkoutropoulou

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Theoni and I'm a data scientist. I have research experience in machine learning with specialization in natural language processing. 

  I am most skilled in: <mark>Python</mark> and as a mathematician in <mark>Matlab</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
